server:
  port: 8090
spring:
  jackson:
    time-zone: GMT+8
  application:
    name: face-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/face?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: haha123.
  redis:
    host: 127.0.0.1
    port: 6379
    password: haha123.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      ylf:
        user: debug
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000