server:
  port: 8089
spring:
  application:
    name: face-manage
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.246.207:3306/face?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: haha123.
  redis:
    host: 120.27.246.207
    port: 6379
    password: haha123.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level: debug
